# Generated by Django 2.1.7 on 2019-03-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190324_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='myapp.Board'),
        ),
    ]
