# Generated by Django 2.1.7 on 2019-03-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190324_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='myapp.Board'),
        ),
    ]
