# Generated by Django 2.1.7 on 2019-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190324_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='board', max_length=30, unique=True),
        ),
    ]
