# Generated by Django 2.1.4 on 2019-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190403_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='name',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
