# Generated by Django 2.1.4 on 2019-04-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190404_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='notice',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Board'),
        ),
    ]
